# Generated by Django 3.2 on 2021-04-12 14:34

from django.db import migrations, models
import django.db.models.deletion
import film.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to=film.models.photo_path)),
            ],
        ),
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to=film.models.photo_film_path)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.TextField(blank=True, max_length=300)),
                ('during', models.SlugField(max_length=10)),
                ('release_date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('silka', models.FileField(upload_to=film.models.photo_film_path)),
                ('actors', models.ManyToManyField(blank=True, related_name='actors', to='film.Actor')),
                ('age_rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film.agerating')),
                ('direc', models.ManyToManyField(blank=True, related_name='directors', to='film.Actor')),
                ('genre', models.ManyToManyField(blank=True, to='film.Genre')),
            ],
        ),
    ]
