# Generated by Django 3.2 on 2021-04-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='film',
            name='age_rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='film.agerating'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film.country'),
        ),
    ]
