# Generated by Django 3.2 on 2021-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20210413_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
