# Generated by Django 3.2 on 2021-04-14 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
