# Generated by Django 3.2 on 2021-05-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20210428_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='content',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
