# Generated by Django 3.2 on 2021-05-02 11:26

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_alter_film_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to=film.models.photo_film_path),
        ),
    ]
