# Generated by Django 3.2 on 2021-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20210509_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
