# Generated by Django 3.2 on 2021-06-28 14:45

from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_auto_20210516_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='silka',
            field=models.FileField(max_length=500, upload_to=film.models.photo_film_path),
        ),
    ]
